name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.2.0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1.0.3
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Unit tests
      run: ./gradlew check
